### ISSUE TITLE
`receptors` directory missing from repo?

### ISSUE THREAD

**Issue by dotsdl** [FoldingAtHome/covid-moonshot#23]
When I execute [`02-generate-poses.py`](https://github.com/FoldingAtHome/covid-moonshot/blob/sprint-5/synthetic-enumeration/sprint-5-retrospective/02-generate-poses.py) on branch `sprint-5` under `sprint-5-retrospective`, I get:

```
sprint-5 [sprint-5-retrospective] ! python 02-generate-poses.py 
Warning: Unable to open "../../receptors/monomer/Mpro-x11498_0A_bound-receptor.oeb.gz" for reading molecules.
Warning: Unable to open receptor file ../../receptors/monomer/Mpro-x11498_0A_bound-receptor.oeb.gz for reading
Warning: Unable to open "../../receptors/monomer/Mpro-x11498_0A_bound-ligand.mol2" for reading molecules.
Traceback (most recent call last):
  File "02-generate-poses.py", line 702, in <module>
    refmol = load_fragment(fragment, title=fragments[fragment])
  File "02-generate-poses.py", line 577, in load_fragment
    raise Exception(f'Could not read {refmol_filename}')
Exception: Could not read ../../receptors/monomer/Mpro-x11498_0A_bound-ligand.mol2
```
The directory does not appear to exist in the repository; is it local to your workspace @jchodera?

**Comment by jchodera** [comment]
@dotsdl : Shoot, I realize I never responded to this!

The `covid-moonshot/receptors/` path is generated by the [`covid-moonshot/scripts/00-prep-all-receptors.py`](https://github.com/FoldingAtHome/covid-moonshot/blob/master/scripts/00-prep-all-receptors.py) script, and it's possible the paths have changed since sprint-5.

We also need to update the infrastructure to use the new [`fah_prep`](https://github.com/choderalab/fah_prep) tool for preparing the `receptors/` structures from @RobertArbon. This tool can correctly handle both the `x` (monomer in asymmetric unit) and `P` (dimer in asymmetric unit) crystal forms.
